# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'sqlite3'
gem 'will_paginate', '~> 3.0.pre4'
gem 'rspec','~>1.3.1'
